### ISSUE TITLE
Slow WIFI speed.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [r5n/Hackintosh-dell-7373#3]
https://github.com/OpenIntelWireless/itlwm
is almost 100% speed but no app store access.

https://github.com/RehabMan/OS-X-Null-Ethernet
is almost 30% speed but app store access.

And then, I want to use itlwm with app store access.
Do you know about something?

Thanks.

**Comment by iamzubin** [comment]
Idk, store works on my pc either way
Didn't see that drastic speed drop either
